<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "blog".
 *
 * @property integer $id
 * @property string $name
 * @property string $url
 * @property integer $owner_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property array  $categories_id
 * @property User $owner
 */
class Blog extends \yii\db\ActiveRecord
{
    const URL_VALIDATE = 'urlValidate';

    public $categories_id = [];

    private $videos;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'url', 'owner_id',], 'required'],
            [['owner_id',], 'integer'],
            [['name', 'url'], 'string', 'max' => 255],
            [['name','url'], 'unique'],
            ['url', 'match', 'pattern' => '/^(http(s?):\/\/)?(www\.)?\w+?\.(com|ru)(\/?\w+)+/i'],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['owner_id' => 'id']],
            [['categories_id'],'safe'],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        if(intval($this->id) > 0){
//            $this->categories_id = \common\models\BlogCategoryRelation::find(['blog_id' => $this->id])->all();
//        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'url' => 'URL',
            'category_id' => 'Категория',
            'owner_id' => 'Owner ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function setVideo($video)
    {
        foreach ($video as $v) {
            if($v instanceof Video){
                $v->blog_id = $this->id;
                $v->save();
            }
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(User::className(), ['id' => 'owner_id']);
    }


    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::URL_VALIDATE] = ['url',];
        return $scenarios;
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'] )
                    ->viaTable(BlogCategoryRelation::tableName(), ['blog_id' => 'id']);
    }

    /**
     * Добавляет видео которое будет привязано к текущему блогу, при сохранении
     * @param Video $video
     * @return $this
     */
    public function addVideo(Video $video)
    {
        $this->videos[] = $video;
        return $this;
    }

    /**
     * Удаление привязанных категорий
     */
    public function deleteCategories()
    {
        $_bcr_table = BlogCategoryRelation::tableName();
        Yii::$app->db->createCommand("DELETE FROM {$_bcr_table} WHERE blog_id={$this->id}")
            ->query();

    }

    /**
     * Сохранение отношения категорий
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        $this->deleteCategories();
        if($categories = Category::findAll($this->categories_id)){
            foreach ($categories as $category){
                $blog_category_relation = new BlogCategoryRelation();
                $blog_category_relation->blog_id = $this->id;
                $blog_category_relation->category_id = $category->id;
                $blog_category_relation->save();
            }
        }
    }

    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => 'created_at',
                    ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
                ],
                'value' => function() { return date('Y-m-d H:m:i'); },
            ],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVideo()
    {
        return Video::findOne(['blog_id' => $this->id]);
    }
}
